### ISSUE TITLE
TypeError: Cannot read property 'getSegmentedPoints' of undefined

### ISSUE THREAD

**Issue by hetsketch** [qdsang/ttf2svg#8]
Hi! I've written plugin for Gulp based on your lib and got an issue while convert this file. Also trying convert with cmd but error still present. File is in zip.

 var segmentedPoints = glyph.getSegmentedPoints();
                                                   ^
TypeError: Cannot read property 'getSegmentedPoints' of undefined
    at C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\lib\Glyph.js:177:31
    at Array.forEach (native)
    at Glyph.getSegmentedPoints (C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\lib\Glyph.js:175:19)
    at Glyph.toSVGPath (C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\lib\Glyph.js:198:22)
    at C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\lib\Font.js:96:18
    at Array.forEach (native)
    at C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\lib\Font.js:84:24
    at Array.forEach (native)
    at Font.getCodeAndGlyph (C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\lib\Font.js:83:18)
    at TTF2SVG._init (C:\Users\hetsketch\AppData\Roaming\npm\node_modules\ttf2svg\src\ttf2svg.js:28:21)

**Comment by hetsketch** [comment]
[Roboto-Thin.zip](https://github.com/qdsang/ttf2svg/files/690926/Roboto-Thin.zip)

**Comment by qdsang** [comment]
@hetsketch fix ok

**Comment by hetsketch** [comment]
@qdsang thanks!
